# Generated by Django 3.2.23 on 2023-11-26 16:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0010_alter_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_subject', models.CharField(max_length=100)),
                ('referral_description', models.TextField()),
                ('introduced_person_name', models.CharField(max_length=100)),
                ('introduced_person_company', models.CharField(max_length=100)),
                ('introduced_person_email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('introduced_person_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='GB', unique=True)),
                ('introduced_person_alternative_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='GB', unique=True)),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('is_percentage_editable', models.BooleanField(default=True)),
                ('is_agreed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('referral_receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to='userprofile.userprofile')),
                ('referral_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='userprofile.userprofile')),
            ],
        ),
    ]
