# Generated by Django 3.2.23 on 2023-11-26 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsmodel',
            name='expected_completion_date',
            field=models.DateField(null=True, validators=[django.core.validators.RegexValidator('\\d{4}-\\d{2}-\\d{2}', message='Enter a valid date format (DD-MM-YYYY)')]),
        ),
    ]
