# Generated by Django 3.2.23 on 2023-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referralsmodel_expected_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsmodel',
            name='estimated_commsion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
