# Generated by Django 3.2.23 on 2023-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermailbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
