# Generated by Django 3.2.23 on 2023-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermailbox', '0002_auto_20231127_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='conversation_subject',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
