# Generated by Django 3.2.23 on 2023-11-23 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0010_alter_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_subject', models.CharField(max_length=100)),
                ('meeting_description', models.TextField()),
                ('meeting_location', models.CharField(max_length=100)),
                ('meeting_date', models.DateField(validators=[django.core.validators.RegexValidator('\\d{2}-\\d{2}-\\d{4}', message='Enter a valid date format (DD-MM-YYYY)')])),
                ('meeting_time', models.TimeField(validators=[django.core.validators.RegexValidator('\\d{2}:\\d{2}', message='Enter a valid time format (HH:MM)')])),
                ('meeting_duration', models.CharField(choices=[('30_mins', '30 mins'), ('45_mins', '46 mins'), ('60_mins', '1 hour'), ('75_mins', '1 hour 15 mins'), ('30_mins', '1 hour 30 mins'), ('30_mins', '1 hour 45 mins'), ('30_mins', '2 hours MAX')], default='', max_length=50)),
                ('is_accepted', models.BooleanField(default=False)),
                ('additional_notes', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_receiver', to='userprofile.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_sender', to='userprofile.userprofile')),
            ],
        ),
    ]
