# Generated by Django 3.2.23 on 2023-11-23 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meeting_date',
            field=models.DateField(validators=[django.core.validators.RegexValidator('\\d{4}-\\d{2}-\\d{2}', message='Enter a valid date format (DD-MM-YYYY)')]),
        ),
    ]
