# Generated by Django 3.2.23 on 2023-11-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231123_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-meeting_date']},
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meeting_duration',
            field=models.CharField(choices=[('30_mins', '30 mins'), ('45_mins', '46 mins'), ('60_mins', '1 hour'), ('75_mins', '1 hour 15 mins'), ('90_mins', '1 hour 30 mins'), ('105_mins', '1 hour 45 mins'), ('120_mins', '2 hours MAX')], default='', max_length=50),
        ),
    ]
