# Generated by Django 3.2.23 on 2023-11-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20231125_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
