# Generated by Django 3.2.23 on 2023-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_archivebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_archived',
            field=models.BooleanField(default=''),
        ),
        migrations.DeleteModel(
            name='ArchiveBooking',
        ),
    ]
