# Generated by Django 3.2.23 on 2023-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20231125_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
