# Generated by Django 3.2.23 on 2023-11-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='meeting_duration',
            field=models.CharField(choices=[('30_mins', '30 mins'), ('45_mins', '46 mins'), ('60_mins', '1 hour'), ('75_mins', '1 hour 15 mins'), ('90_mins', '1 hour 30 mins'), ('105_mins', '1 hour 45 mins'), ('120_mins', '2 hours MAX')], default='30_mins', max_length=50),
        ),
    ]
