# Generated by Django 3.2.23 on 2023-11-20 03:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0003_rename_comapny_website_userprofile_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile_reviewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
