# Generated by Django 3.2.23 on 2023-12-01 04:48

import cloudinary.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20231201_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alternative_company_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Alternative contact number for the company.', max_length=128, null=True, region='GB', unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_bio',
            field=models.TextField(help_text='Provide a brief bio about your company.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_contact_email',
            field=models.EmailField(help_text='Enter your company contact email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_hero_picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', help_text='Upload a hero picture for your company.', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(help_text='Enter your company name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_services_post',
            field=models.TextField(help_text='Post about your company services.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_website',
            field=models.URLField(help_text='Enter your company website URL.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_user_email',
            field=models.BooleanField(default=True, help_text='Display user email publicly.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_about',
            field=models.TextField(default='Come say hi to me...', help_text='Tell us about yourself.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_img',
            field=cloudinary.models.CloudinaryField(default='placeholder', help_text='Upload your profile picture.', max_length=255, verbose_name='image'),
        ),
    ]
